quotes:
  - origin: 'Thomas Piketty, Capital in the 21st Century'
    quote:  'On his deathbed in 1821, abandoned by his daughters Delphine and
            Anastasie, old Goriot still dreamt of juicy investments in the 
            pasta business in Odessa.'

  - origin: 'Steinn Steinarr, Passíusálmur 51'
    quote:  'Og stúlka með sægræn augu segir við mig: Skyldi manninnum ekki 
            leiðast að láta krossfesta sig?'

  - origin: 'Steinn Steinarr, Tíminn og Vatnið'
    quote:  'Og sólin gekk yfir grunlaust blómið á gulum skóm'

  - origin: 'Graphic Futanari'
    quote:  'Ömurlega leiðinleg. Ekki koma við mig.'

  - origin: 'Frank Herbert, Dune'
    quote:  'Fear is the mind-killer. Fear is the little-death that brings total obliteration.'

  - origin: 'Bertrand Russell, A History of Western Philosophy'
    quote:  'Some, whose scholarly austerity is unbending, will conclude 
            that books covering a wide field should not be written at all.'

  - origin: 'Gummo # Critical Reception, Wikipedia Article'
    quote:  'Werner Herzog praised the film and talked about being impressed
            by the bacon taped to the wall during the bathtub scene.'

  - origin: 'David Foster Wallace, Consider the Lobster'
    quote:  'As a tourist, you become economically significant but
            existentially loathsome, an insect on a dead thing.'

  - origin: 'William S. Burroughs, The Place of Dead Roads'
    quote:  'England is like some stricken beast too stupid to know it is dead.
            Ingloriously foundering in its own waste products, the backlash and
            bad karma of empire.'

  - origin: 'E.F. Schumacher'
    quote:  'Ever bigger machines, entailing ever bigger concentrations of 
            economic power and exerting ever greater violence against the 
            environment, do not represent progress: they are a denial of wisdom.'

  - origin: 'XXX Rottweiler, Sönn Íslensk Sakamál'
    quote:  'Ég er maðurinn sem brenndi inni Bjarna Ben, Á svörtum lista yfir pólitíska öfgamenn'

  - origin: 'Ellen Ullman, The dumbing-down of programming'
    quote:  'The least and smallest thing the machine could do in the absence of all else, its one last imperative: No operating system! Look for BASIC! It was like happening upon some primitive survival response, a low-level bit of hard wiring, like the mysterious built-in knowledge that lets a blind little mouseling, newborn and helpless, find its way to the teat.'

  - origin: 'Ellen Ullman, The dumbing-down of programming'
    quote:  'We build our computers the way we build our cities -- 
            over time, without a plan, on top of ruins.'

  - origin: 'Karl Marx, The Eighteenth Brumaire of Louis Bonaparte'
    quote:  'The tradition of all dead generations weighs like a nightmare on the brains of the living.'

  - origin: 'Lewis Carroll, Jabberwocky'
    quote:  "\'Twas brillig, and the slithy toves\n    Did gyre and gimble in the wabe..."

  - origin: "Nathan Poe (of Poe\'s Law), Christian Forums"
    quote:  'Good thing you included the winky. Otherwise people might think you are serious.'

  - origin: "Hofstadter\'s Law"
    quote:  "It always takes longer than you expect, even when you take into account Hofstadter's Law."

  - origin: "Benjamin Frankling"
    quote:  "You will observe with concern how long a useful truth may be known, and exist, before it is generally received and practiced on."

  - origin: "Frank Howard -- President of Standard Oil"
    quote:  "We do not feel justified in giving up what has come to the industry like a gift from heaven on the possibility that a hazard may be involved in it."

  - origin: "Matt Christman, Doe6: Women Be Croppin\'"
    quote:  "That's why in the 1800s [anarchists] couldn't stop shooting politicians: Because it felt good!"
