#! /bin/sh

sxhkd -t 1 &

bspc monitor -d A1 A2 A3 A4 A5 B1 B2 B3 B4 B5 C1 C2 C3 C4 C5 D1 D2 D3 D4 D5 E1 E2 E3 E4 E5 

bspc config border_width	0
bspc config window_gap		0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
bspc rule -a feh state=tiled
bspc rule -a zathura state=tiled

feh --bg-fill ~/Pictures/ferns.jpg
